export * from "./ContactPage";
export * from "./GamePage";
export * from "./HomePage";
export * from "./LegalPage";
export * from "./LobbyPage";
export * from "./LoginPage";
export * from "./MyRoomsPage";
export * from "./RegisterPage";
export * from "./RoomPage";